config/routes.rb
Trending::Application.routes.draw do
  get "rooms/index"

  get "room/index"

  get "closet/index"

  get "closet/corporate"

  resources :homes

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users

  devise_scope :user do
    get "/", :to => "devise/registrations#new"
  end

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  attr_accessible :image, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private 
  def stored_location_for(resource_or_scope)
    nil
  end

  def after_sign_in_path_for(resource_or_scope)
    closet_index_path
  end
end

app/controllers/closet_controller.rb
class ClosetController < ApplicationController
  def index
  end

  def friends
  end
  
  def corporate
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render json: @home, status: :created, location: @home }
      else
        format.html { render action: "new" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/myroom_controller.rb
class MyroomController < ApplicationController
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/closet_helper.rb
module ClosetHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/myroom_helper.rb
module MyroomHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/closet/corporate.html.erb
<body>
	<div class="data">
		<br><h1 class="title">Newest trends from your social circle</h1>
		<div class="title">
			<%= link_to 'View trends around the world', closet_index_path %>
		</div>
		<div>
			<%= image_tag('friend1.jpg', :width => '100%', :class => "post") %>
			<%= image_tag('friend2.jpg', :width => '100%', :class => "post")%>
			<%= image_tag('friend3.jpg', :width => '100%', :class => "post")%>
			<%= image_tag('friend4.jpg', :width => '100%', :class => "post")%>
			<%= image_tag('friend5.jpg' , :width => '100%', :class => "post")%>
			<%= image_tag('friend6.jpg', :width => '100%', :class => "post")%>
	</div>
	<div>

</body>



<style>
      body {
    font: 14px "Trebuchet MS", Helvetica, sans-serif;
    padding-top: 50px;
    margin: 0;
    background-image: url("<%= asset_path "dark11.png" %>");
  }
  .data{
        text-align: center;
        background: white;
        position: absolute;
        top: 78px;
        width: 1000px;
        left: 50%;
        margin-left: -500px;
    }

  	.post {
        width: 300px;
        margin: 20px 10px 0px 10px;
        cursor: pointer;
    }
   .title{margin-left: 70px;}

</style>

app/views/closet/friends.html.erb
<h1>Closet#friends</h1>
<p>Find me in app/views/closet/corporate.html.erb</p>

app/views/closet/index.html.erb
<body>
	<div class="data">
		<br><h1 class="title">Newest trends all over the world</h1>
		<div class="title">
			<%= link_to 'Filter by your social circle', closet_corporate_path %>
		</div>
		<div>
		  		<%= image_tag('dress1.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('dress2.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('dress3.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('dress14.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('dress5.jpg' , :width => '100%', :class => "post")%>
		  		<%= image_tag('dress6.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('dress7.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('dress8.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('dress9.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('dress10.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('dress11.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('friend1.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('dress13.jpg', :width => '100%', :class => "post")%>
		  		<%= image_tag('friend4.jpg', :width => '100%', :class => "post")%>
		  </div>
	</div>

</body>



<style>
      body {
    font: 14px "Trebuchet MS", Helvetica, sans-serif;
    padding-top: 50px;
    margin: 0;
    background-image: url("<%= asset_path "dark11.png" %>");
  }
  .data{
        text-align: center;
        background: white;
        position: absolute;
        top: 78px;
        width: 1000px;
        left: 50%;
        margin-left: -500px;
    }

  	.post {
        width: 300px;
        margin: 20px 10px 0px 10px;
        cursor: pointer;
    }
   .title{margin-left: 70px;}
   #topbar {
      background-color: #7e8631;
      margin: 0;
      position: fixed;
      z-index: 100;
      top: 0;
      padding: 0;
      height: 78px;
      width: 100%;
    }
    header {
        position: absolute;
        left: 50%;
        top: 0%;
        height: 50px;
        width: 1000px;
        margin-left: -500px;
    }
    header button {
      background: #7e8631;
      height: 78px;
      padding: 0px 20px;
      margin: 0px;
      cursor: pointer;
      float: right;
    }
    header button:hover {
        background: #fff  ;
    }

</style>

app/views/homes/index.html.erb
<style>
      body {
    font: 14px "Trebuchet MS", Helvetica, sans-serif;
    padding: 0;
    margin: 0;
  }
  #welcome {
    width: 100%;
    height: 100%;
    background-image: url(<%= asset_path "welcome.jpg" %>);
    background-size: cover;
    position: fixed;
    top: 0;
    left: 0;
  }
  #overlay {
    position: fixed;
    top: 0;
    left: 0;
    background-image: url(<%= asset_path "dark11.png"%>);
    width: 100%;
    height: 100%;
  }
  #topbar {
    background-color: #fff;
    margin: 0;
    position: fixed;
    top: 0;
    padding: 0;
    height: 50px;
    width: 100%;
  }
  #topbar #login {
    cursor: pointer;
    float: right;
    margin-right: 100px;
  } 
  #left {
    position: absolute;
    top: 50%;
    left: 50%;
    width: 300px;
    margin-left: -400px;
  }
  #left input {
    width: 300px;
  }
  #left button {
    width: 300px;
  }
  #left hr {
    width: 300px;
  }
  #left #fblogin {
    background-color: #00f;
    color: #fff;
  }
  #left #twitterlogin {
    background-color: lightblue;
    color: #fff;
  }
  #right {
    position: absolute;
    top: 50%;
    left: 50%;
    margin-left: 100px;
    width: 300px;
  }
  #right #explore {
    width: 300px;
  }
  #signinOverlay {
    z-index: 99;
    background: #fff;
    opacity: 0.8;
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
  }
  #signinPopUp {
    background: #808080;
    width: 320px;
    padding: 10px;
    height: 200px;
    z-index: 100;
    position: fixed;
    top: 50%;
    left: 50%;
    margin-left: -150px;
    margin-top: -100px;
  }
  #signinPopUp input,
  #signinPopUp button {
    margin-top: 20px;
    width: 300px;
  }
  #signinPopUp .close {
    cursor: pointer;
    float: right;
  }

  .hidden {
      display: none;
  }

</style>

<body>
    <section id="content" >
    <div id="welcome"></div>
    <div id="overlay"></div>
    <div id="topbar"> 
        <img id="logo" />
        <% if user_signed_in? %>
          <h4 id="login"> <%= link_to("Logout", destroy_user_session_path, :method => :delete) %> </h4>
        <% else %>
          <h4 id="login" >
            SIGN IN
          </h4>
        <% end %>
    </div>

    <div id="left">
        <button id="fblogin">
            FACEBOOK SIGN UP
        </button>
        <%= link_to "Twitter Sign Up", user_omniauth_authorize_path(:twitter), :id => "twitterlogin" %>
        <hr />
        <form name="signUpForm">
            <input  name="email" required type="email" placeholder="email"  />
            <input name="password" required  type="password"  placeholder="password" />
            <input  name="confirm" required  type="password" placeholder="re-type password" />
            
            <button >SIGN UP</button>
        </form>
    </div>
    <div id="right">
        <button id="explore">
            <h2>EXPLORE</h2>
        </button>
    </div>

    <div id="signinOverlay" class="hidden" ></div>

    <div id="signinPopUp"  class="hidden" >
        <span class="close" >X</span>
        <form name="signInForm">
            <input name="email" required type="email" placeholder="email"  />
            <input  name="password" required  type="password" placeholder="password" />
            <button >SIGN IN</button>
        </form>
    </div>
    </section>  
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trending</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style>
  	#topbar {
    background-color: #fff;
    margin: 0;
    position: fixed;
    top: 0;
    padding: 0;
    height: 50px;
    width: 100%;
  }
  #topbar #login {
    cursor: pointer;
    float: right;
    margin-right: 100px;
  }
  </style>
</head>
<body>

	<div id="topbar"> 
        <img id="logo" />
        <% if user_signed_in? %>
          <h4 id="login"> <%= link_to("Logout", destroy_user_session_path, :method => :delete) %> </h4>
        <% else %>
          <h4 id="login" >
            SIGN IN
          </h4>
        <% end %>
    </div>

<%= yield %>

</body>
</html>

app/views/room/index.html.erb
<html>
  <head>
    <title>  My room | Trendz </title>

    <style>
    body {
      font: 20px "Trebuchet MS", Helvetica, sans-serif;
      padding: 0;
      margin: 0;
    }
    button {
      background: #7e8631;
      height: 78px;
      padding: 0px 20px;
      margin: 0px;
      cursor: pointer;
      float: right;
      color: white;
    }
    button:hover {
        background: white;
        color: black;
    }
    input {
        outline: #BDB9BC solid thin;
        margin: 5px 0px;
        padding: 10px;
        border: none;
    }
    input:focus, area:focus {
        outline: #BDB9BC solid thin;
    }
    #welcome {
      width: 100%;
      height: 100%;
      background-image: url(<%= asset_path "welcome.jpg" %>);
      background-size: cover;
      position: fixed;
      top: 0;
      left: 0;
    }
    #overlay {
      position: fixed;
      top: 0;
      left: 0;
      background-image: url(<%= asset_path "dark11.png"%>);
      width: 100%;
      height: 100%;
    }
    #topbar {
      background-color: #7e8631;
      margin: 0;
      z-index: 100;
      position: fixed;
      top: 0;
      padding: 0;
      height: 78px;
      width: 100%;
    }
    header {
        position: absolute;
        left: 50%;
        top: 0%;
        height: 50px;
        width: 1000px;
        margin-left: -500px;
    }
    header button {
      background: #7e8631;
      height: 78px;
      padding: 0px 20px;
      margin: 0px;
      cursor: pointer;
      float: right;
    }
    header button:hover {
        background: #fff  ;
    }
    .content {
        position: absolute;
        left: 50%;
        top: 80
        height: 400px;
        width: 1000px;
        margin-left: -500px;
        margin-top: -175px;
    }
    .contOver {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background: white;
        opacity: 0.75;
    }

    .hidden {
        display: none;
    }
    
    .myroom {
        background: #fff;
        position: fixed;
        left: 50%;
        top: 78px;
        height: 763px;
        width: 1000px;
        margin-left: -500px;
    }
    
    .myroom img {
        position: absolute;
        bottom: 0;
        width: 1000px;
    }
    
    #profPicCont {
        background: #7e8631;
        position: absolute;
        top: 50px;
        left: 50px;
        width: 100px;
        height: 100px;
        border: 1px grey solid;
        
    }
    #profPicCont img {
        width: 90px;
        auto: 90px;
        margin: 5px;   
    }
    .myroom .desc {
        color: #7e8631;
        position: absolute;
        top: 17px;
        left: 190px;
        -webkit-text-stroke: 0px black;
    }
        #logo {
        float: left;
        height: 78px;
    }


    </style>
    
    
	</head>
   <body>
   	<section id="content" >
        <div id="overlay"></div>
        <div id="topbar"> 
            <header>
                <%= image_tag("logo.png", :id => 'logo') %>
                <button id="login" >
                    <h3> Log Out</h3>
                </button>
                <button id="login" >
                    <h3> Profile</h3>
                </button>
                <button id="af" >
                    <h3> <%= link_to 'My room', rooms_index_path, :id => 'af', :style => 'text-decoration:none, color:black'%> </h3>
                </button>
                <button id="af" >
                    <h3> <%= link_to 'Explore', closet_index_path, :id => 'af', :style => 'text-decoration:none, color:black'%> </h3>
                </button>
                <button id="af" >
                    <h3><%= link_to 'Now Trending', closet_index_path, :id => 'af', :style => 'text-decoration:none, color:black' %></h3>
                </button>
            </header>
         </div>

            <div class="myroom">
                <%= image_tag('myroom1.jpg', :usemap => '#roommap')%>

                <map name="roommap">
                  <area shape="closet" coords="150,200,320,250" alt="My closet" href="/rooms/index">
                  <!--area shape="shelf" coords="0,0,200,50" alt="My shelf" href="_self">
                  <area shape="desk" coords="0,0,200,50" alt="My desk" href="_self">
                  <area shape="decor" coords="0,0,200,50" alt="My decor" href="_self"-->
                </map>
                <div id="profPicCont">
                    <%= image_tag('prof.jpg') %>
                </div>
                <div class="desc">
                    <h1> Frankie's room </h1>
                    <span> #hipster #books #beer #plaid</span>
                </div>

            </div>
      
    </section>	
</body>
</html>

app/views/rooms/index.html.erb
<html>
  <head>
    <title>  My room | Trendz </title>

    <style>
    body {
      font: 20px "Trebuchet MS", Helvetica, sans-serif;
      padding: 0;
      margin: 0;
    }
    button {
        background: #BDB9BC;
        outline: none;
        cursor: pointer;
        padding: 0;
        border: none;
        margin: 5px 0px;
        height: 50px;
    }
    button:hover {
        background-color: white;
    }
    button:active {
        background-color: #BDB9BC;
    }
    input {
        outline: #BDB9BC solid thin;
        margin: 5px 0px;
        padding: 10px;
        border: none;
    }
    input:focus, area:focus {
        outline: #BDB9BC solid thin;
    }
    #welcome {
      width: 100%;
      height: 100%;
      background-image: url("<%= asset_path "welcome.jpg" %>");
      background-size: cover;
      position: fixed;
      top: 0;
      left: 0;
    }
    #overlay {
      position: fixed;
      top: 0;
      left: 0;
      background-image: url("<%= asset_path "dark11.png"%>");
      width: 100%;
      height: 100%;
    }
    #topbar {
      background-color: #7e8631;
      margin: 0;
      position: fixed;
      z-index: 100;
      top: 0;
      padding: 0;
      height: 78px;
      width: 100%;
    }
    header {
        position: absolute;
        left: 50%;
        top: 0%;
        height: 50px;
        width: 1000px;
        margin-left: -500px;
    }
    header button {
      background: #7e8631;
      height: 78px;
      padding: 0px 20px;
      margin: 0px;
      cursor: pointer;
      float: right;
    }
    header button:hover {
        background: #fff  ;
    }
    .content {
        position: absolute;
        left: 50%;
        top: 80
        height: 400px;
        width: 1000px;
        margin-left: -500px;
        margin-top: -175px;
    }
    .contOver {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background: white;
        opacity: 0.8;
    }

    .hidden {
        display: none;
    }
    
    .myroom {
        background: #fff;
        position: absolute;
        left: 50%;
        top: 78px;
        width: 1000px;
        margin-left: -500px;
    }
    #header {
        background-image: url("<%= asset_path "closet.jpg" %>");
        position: absolute;
        top: 0px;
        width: 100%;
        left: 0px;
        height: 200px;
    }
    #profPicCont {
        background: #7e8631;
        position: absolute;
        top: 50px;
        left: 50px;
        width: 100px;
        height: 100px;
        border: 1px grey solid;
    }
    #profPicCont img {
       
        margin: 5px;
        height:90px;   
    }
    #header .desc {
        color: #7e8631;
        position: absolute;
        top: 17px;
        left: 190px;
        -webkit-text-stroke: 0px black;
    }
    .table {
        text-align: center;
        background: white;
        position: absolute;
        top: 200px;
        width: 100%;
    }
    .post {
        width: 300px;
        margin: 20px 10px 0px 10px;
        cursor: pointer;
    }
    </style>
    
    
	</head>
   <body>
   	<section id="content" >
        <div id="overlay"></div>
        <div id="topbar"> 
            <header>
               <%= image_tag("logo.png", :id => 'logo') %>
                <button id="login" >
                    <h3> Log Out</h3>
                </button>
                <button id="login" >
                    <h3> Profile</h3>
                </button>
                <button id="af" >
                    <h3> <%= link_to 'My room', room_index_path, :id => 'af', :style => 'text-decoration:none, color:black'%> </h3>
                </button>
                <button id="af" >
                    <h3> <%= link_to 'Explore', closet_index_path, :id => 'af', :style => 'text-decoration:none, color:black'%> </h3>
                </button>
                <button id="af" >
                    <h3><%= link_to 'Now Trending', closet_index_path, :id => 'af', :style => 'text-decoration:none, color:black' %></h3>
                </button>
            </header>
         </div>

        <div class="myroom">
            <div id="header">
                <div class="contOver"></div>
                <div id="profPicCont">
                    <%= image_tag("prof.jpg") %>
                </div>
                <div class="desc">
                    <h1> Melanie's closet </h1>
                    <span> #hipster #books #beer #plaid</span>
                </div>
            </div>
            <div class="table">
            	<%= image_tag('add.png', :class => 'post newPost') %>
            	<%= image_tag('friends9.jpg', :class => 'post', :style => "height:450px") %>
            	<%= image_tag('friend8.jpg', :class => 'post') %>
            	<%= image_tag('friend2.jpg', :class => 'post' )%>
            	<%= image_tag('friends10.jpg', :class => 'post') %>
            	<%= image_tag('friend113.jpg', :class => 'post', :style => "height:400px") %>
            </table>

        </div>
      
    </section>	
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.image %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Image:</b>
  <%= @user.image %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>